#
# kitty.conf
#

# KEYBINDS

map ctrl+shift+v        paste_from_clipboard
map ctrl+shift+c        copy_to_clipboard
map ctrl+shift+enter    new_window_with_cwd
map ctrl+shift+t        new_tab_with_cwd
map ctrl+shift+q        close_window
map ctrl+shift+h        neighboring_window left
map ctrl+shift+l        neighboring_window right
map ctrl+shift+k        neighboring_window up
map ctrl+shift+j        neighboring_window down

# Fonts

font_family       JetBrains Mono
font_size         16

# Fallback Fonts

font_family       Noto Sans Mono CJK JP
font_family       Noto Sans Mono CJK KR
font_family       Noto Sans Mono CJK SC
font_family       Noto Sans Mono CJK TC

## Theme: Solarized Dark

# Paddings

window_padding_width 10
window_border_width 0
allow_remote_control yes

# The basic colors

foreground              #839496
background              #002B36
selection_foreground    #002B36
selection_background    #93A1A1

# Cursor colors

cursor                  #93A1A1
cursor_text_color       #002B36

# Cursor animations

cursor_trail 3
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

# URL underline color when hovering with mouse

url_color               #268BD2

# Kitty window border colors

active_border_color     #93A1A1
inactive_border_color   #586E75
bell_border_color       #B58900

# Confirm to close window

confirm_os_window_close 0

# OS Window titlebar colors

wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors

active_tab_foreground   #002B36
active_tab_background   #93A1A1
inactive_tab_foreground #839496
inactive_tab_background #073642
tab_bar_background      #002B36
tab_bar_style hidden

# Colors for marks

mark1_foreground #002B36
mark1_background #268BD2
mark2_foreground #002B36
mark2_background #6C71C4
mark3_foreground #002B36
mark3_background #2AA198

# The 16 terminal colors

# black

color0  #073642
color8  #586E75

# red

color1  #DC322F
color9  #CB4B16

# green

color2  #859900
color10 #B58900

# yellow

color3  #B58900
color11 #CB4B16

# blue

color4  #268BD2
color12 #839496

# magenta

color5  #D33682
color13 #6C71C4

# cyan

color6  #2AA198
color14 #93A1A1

# white

color7  #EEE8D5
color15 #FDF6E3

