#
# kitty.conf
#

# KEYBINDS
map ctrl+shift+v        paste_from_clipboard
map ctrl+shift+c        copy_to_clipboard
map ctrl+shift+enter    new_window_with_cwd
map ctrl+shift+t        new_tab_with_cwd
map ctrl+shift+q        close_window
map ctrl+shift+h        neighboring_window left
map ctrl+shift+l        neighboring_window right
map ctrl+shift+k        neighboring_window up
map ctrl+shift+j        neighboring_window down

# Fonts
font_family       JetBrains Mono
font_size         16

# Fallback Fonts
font_family       Noto Sans Mono CJK JP
font_family       Noto Sans Mono CJK KR
font_family       Noto Sans Mono CJK SC
font_family       Noto Sans Mono CJK TC

## Theme: Catppuccin Mocha

# Paddings
window_padding_width 10
window_border_width 0
allow_remote_control yes

# The basic colors
foreground              #FFFFFF
background              #000000
selection_foreground    #000000
selection_background    #FFFFFF

# Cursor colors
cursor                  #FFFFFF
cursor_text_color       #000000

# Cursor animations
cursor_trail 3
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

# URL underline color when hovering with mouse
url_color               #4DA3FF

# Kitty window border colors
active_border_color     #FFFFFF
inactive_border_color   #555555
bell_border_color       #FFD700

# Confirm to close window
confirm_os_window_close 0

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #000000
active_tab_background   #FFFFFF
inactive_tab_foreground #FFFFFF
inactive_tab_background #111111
tab_bar_background      #000000
tab_bar_style hidden

# Colors for marks
mark1_foreground #000000
mark1_background #4DA3FF
mark2_foreground #000000
mark2_background #C084FC
mark3_foreground #000000
mark3_background #2DD4BF

# The 16 terminal colors

# black
color0  #000000
color8  #666666

# red
color1  #FF5555
color9  #FF7777

# green
color2  #50FA7B
color10 #69FF94

# yellow
color3  #F1FA8C
color11 #FFFFA5

# blue
color4  #61AFEF
color12 #7DCFFF

# magenta
color5  #FF79C6
color13 #FF92D0

# cyan
color6  #8BE9FD
color14 #A4FFFF

# white
color7  #E6E6E6
color15 #FFFFFF
