#
# kitty.conf
#

# KEYBINDS
map ctrl+shift+v        paste_from_clipboard
map ctrl+shift+c        copy_to_clipboard
map ctrl+shift+enter    new_window_with_cwd
map ctrl+shift+t        new_tab_with_cwd
map ctrl+shift+q        close_window
map ctrl+shift+h        neighboring_window left
map ctrl+shift+l        neighboring_window right
map ctrl+shift+k        neighboring_window up
map ctrl+shift+j        neighboring_window down

# Fonts
font_family       JetBrains Mono
font_size         16

# Fallback Fonts
font_family       Noto Sans Mono CJK JP
font_family       Noto Sans Mono CJK KR
font_family       Noto Sans Mono CJK SC
font_family       Noto Sans Mono CJK TC

## Theme: Catppuccin Mocha

# Paddings
window_padding_width 10
window_border_width 0

# The basic colors
foreground              #CDD6F4
background              #1E1E2E
selection_foreground    #1E1E2E
selection_background    #F5E0DC

# Cursor colors
cursor                  #F5E0DC
cursor_text_color       #1E1E2E

# Cursor animations
cursor_trail 3
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

# URL underline color when hovering with mouse
url_color               #89B4FA

# Kitty window border colors
active_border_color     #CBA6F7
inactive_border_color   #6C7086
bell_border_color       #F9E2AF

# Confirm to close window
confirm_os_window_close 0

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #1E1E2E
active_tab_background   #CBA6F7
inactive_tab_foreground #CDD6F4
inactive_tab_background #181825
tab_bar_background      #1E1E2E
tab_bar_style hidden

# Colors for marks
mark1_foreground #1E1E2E
mark1_background #89B4FA
mark2_foreground #1E1E2E
mark2_background #CBA6F7
mark3_foreground #1E1E2E
mark3_background #94E2D5

# The 16 terminal colors

# black
color0  #45475A
color8  #585B70

# red
color1  #F38BA8
color9  #F38BA8

# green
color2  #A6E3A1
color10 #A6E3A1

# yellow
color3  #F9E2AF
color11 #F9E2AF

# blue
color4  #89B4FA
color12 #89B4FA

# magenta
color5  #F5C2E7
color13 #F5C2E7

# cyan
color6  #94E2D5
color14 #94E2D5

# white
color7  #BAC2DE
color15 #A6ADC8
